# Generated by Django 6.0.6 on 2026-07-03 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0012_studyplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('Google', 'Google'), ('Microsoft', 'Microsoft'), ('Amazon', 'Amazon'), ('Infosys', 'Infosys'), ('TCS', 'TCS'), ('Accenture', 'Accenture'), ('Wipro', 'Wipro')], max_length=100)),
                ('role', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Java Developer', 'Java Developer'), ('Data Analyst', 'Data Analyst')], max_length=100)),
                ('question', models.TextField()),
                ('practiced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
