# Generated by Django 6.0.6 on 2026-07-03 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0013_interviewquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='company',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='role',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Coding', 'Coding'), ('HR', 'HR'), ('Aptitude', 'Aptitude')], default='Technical', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('Google', 'Google'), ('Microsoft', 'Microsoft'), ('Amazon', 'Amazon'), ('Infosys', 'Infosys'), ('TCS', 'TCS'), ('Accenture', 'Accenture'), ('Wipro', 'Wipro'), ('Cognizant', 'Cognizant'), ('Capgemini', 'Capgemini')], max_length=100)),
                ('role', models.CharField(choices=[('Python Developer', 'Python Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Java Developer', 'Java Developer'), ('Data Analyst', 'Data Analyst')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='studyplanner.interviewsession'),
            preserve_default=False,
        ),
    ]
